/**
 * Static instructional content for the standard single-player Omi tutorial.
 * Keep this content aligned with the authoritative standard rules in src/engine/.
 */
export const TUTORIAL_STEPS = Object.freeze([
    {
        id: 'teams',
        kicker: 'Step 01 · The table',
        title: 'Four players. Two teams.',
        body: 'Omi is a partnership trick-taking game. You sit opposite your partner while the two remaining seats form the opposing team.',
        bullets: [
            'South (you) and North are partners.',
            'East and West are partners.',
            'Partners combine their tricks and tokens.',
        ],
        visual: 'teams',
        caption: 'Your partner always sits opposite you.',
    },
    {
        id: 'deck',
        kicker: 'Step 02 · The deck',
        title: '32 cards only.',
        body: 'Standard Omi uses the four normal suits, but only ranks Seven through Ace. Each player ultimately receives eight cards.',
        bullets: [
            'Suits: Spades, Hearts, Diamonds and Clubs.',
            'Eight ranks per suit: 7, 8, 9, 10, J, Q, K, A.',
            'No Joker is used in Standard Mode.',
        ],
        visual: 'deck',
        caption: 'Four suits × eight ranks = 32 cards.',
    },
    {
        id: 'ranking',
        kicker: 'Step 03 · Card strength',
        title: 'Ace is highest.',
        body: 'When cards of the same relevant suit compete in a trick, rank decides which card is stronger.',
        bullets: [
            'Highest to lowest: A, K, Q, J, 10, 9, 8, 7.',
            'Suit rules and trump are checked before rank.',
        ],
        visual: 'ranking',
        caption: 'Strength increases from Seven to Ace.',
    },
    {
        id: 'trump',
        kicker: 'Step 04 · Deal and trump',
        title: 'Choose trump after four cards.',
        body: 'The dealer gives four cards to every player. The player to the dealer’s right must choose a trump suit from those first four cards. Then everyone receives four more cards.',
        bullets: [
            'The trump chooser cannot see the second four cards first.',
            'Passing is not available in Standard Mode.',
            'After the second deal, every player has eight cards.',
        ],
        visual: 'trump',
        caption: 'Example: Hearts are chosen as trump.',
    },
    {
        id: 'leading',
        kicker: 'Step 05 · Leading',
        title: 'One card starts the trick.',
        body: 'The first player leads one card. That card establishes the lead suit. Play continues counter-clockwise until all four players have played once.',
        bullets: [
            'Four played cards make one trick.',
            'The trump chooser leads the first trick of the hand.',
            'The trick winner leads the next trick.',
        ],
        visual: 'leading',
        caption: 'A Club lead means Clubs are the lead suit.',
    },
    {
        id: 'follow-suit',
        kicker: 'Step 06 · Following suit',
        title: 'You must follow suit.',
        body: 'If you hold at least one card from the lead suit, you must play that suit. You may play another suit only when you have none of the lead suit.',
        bullets: [
            'Legal cards remain available to play.',
            'Off-suit cards are illegal while you still hold the lead suit.',
            'When void in the lead suit, you may discard or play trump.',
        ],
        visual: 'follow',
        caption: 'Clubs are led, so the Club cards are the legal choices.',
    },
    {
        id: 'trump-power',
        kicker: 'Step 07 · Trump',
        title: 'Trump changes the trick.',
        body: 'Any trump card beats every non-trump card in the trick. If more than one trump is played, the highest-ranked trump wins.',
        bullets: [
            'Trump can win even when it has a low rank.',
            'Among trump cards, normal rank order still applies.',
            'You still must follow the lead suit when you can.',
        ],
        visual: 'trump-power',
        caption: 'Hearts are trump: 7♥ beats A♣ in this example.',
    },
    {
        id: 'resolve-trick',
        kicker: 'Step 08 · Trick resolution',
        title: 'Read the trick in order.',
        body: 'First check whether any trump card was played. If there is no trump, only cards of the lead suit can win.',
        bullets: [
            'Trump present → highest trump wins.',
            'No trump → highest card of the lead suit wins.',
            'Unrelated off-suit cards cannot win without being trump.',
        ],
        visual: 'resolve',
        caption: 'Spades were led; no trump appears; A♠ wins.',
    },
    {
        id: 'scoring',
        kicker: 'Step 09 · Hand scoring',
        title: 'Eight tricks decide the hand.',
        body: 'After all eight tricks, the two teams compare totals. Standard Omi awards different base tokens depending on whether the trump-calling team or defending team wins.',
        bullets: [
            'Trump-calling team wins 5–7 tricks → 1 base token.',
            'Defending team wins 5–7 tricks → 2 base tokens.',
            'A complete 8-trick Kapothi → 3 base tokens.',
        ],
        visual: 'scoring',
        caption: 'Carry tokens, when present, are added to the next decisive award.',
    },
    {
        id: 'tie-and-target',
        kicker: 'Step 10 · Tie and match target',
        title: 'A 4–4 hand carries forward.',
        body: 'A tied hand awards no tokens immediately. Instead, it adds one carry token to the next decisive hand. Standard matches target ten tokens.',
        bullets: [
            '4–4 → no immediate token award.',
            'Each tied hand adds one carry token.',
            'The carry is added to the next decisive hand, then reset.',
            'The match target is 10 tokens.',
        ],
        visual: 'target',
        caption: 'First team to reach the 10-token target wins the match.',
    },
    {
        id: 'strategy',
        kicker: 'Step 11 · Beginner strategy',
        title: 'Now learn by playing.',
        body: 'The rules are simple, but strong Omi play comes from memory, timing and partnership awareness. Start by watching the public information on the table.',
        bullets: [
            'Remember high cards that have already been played.',
            'Notice when a player cannot follow a suit.',
            'Avoid wasting strong trump when your partner is already winning.',
            'Use the Tutorial again whenever you want a refresher.',
        ],
        visual: 'ready',
        caption: 'You are ready for a Standard Omi match.',
    },
]);
